steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vanns-demo/subgraph3', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vanns-demo/subgraph3']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'subgraph3', '--image', 'gcr.io/vanns-demo/subgraph3','--allow-unauthenticated', '--region', 'us-east1']
images:
- gcr.io/vanns-demo/subgraph3